/**
 * Runtime helpers for build-time optimized styles
 * This file is auto-generated by the Babel plugin
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

import { StyleSheet, Platform } from 'react-native';
import { StyleValue } from '../../types';
import { mainStyles } from '../../core/mainStyles';
import { parseArbitraryValue } from '../../core/arbitraryParser';
import { shouldApplyClass, getBaseClassName } from '../../core/platform';

/**
 * Runtime cache for partial template combinations
 * Stores dynamically computed style combinations
 */
const partialCache = new Map<string, any>();

/**
 * Partial template helper
 * Combines pre-computed static styles with runtime dynamic lookups
 *
 * @param staticStyles - Pre-computed style objects from static parts
 * @param dynamicClasses - Dynamic class names from interpolations
 * @returns Combined and flattened style object
 */
export function _rnw_partial(
  staticStyles: StyleValue[],
  dynamicClasses: (string | null | undefined | false)[],
): StyleValue {
  // Create cache key from dynamic classes only
  // Static styles are always the same for a given template
  const cacheKey = dynamicClasses
    .filter((c) => c)
    .join('§');

  // Check cache first
  const cached = partialCache.get(cacheKey);
  if (cached !== undefined) {
    return cached;
  }

  // Start with pre-computed static styles
  const allStyles: StyleValue[] = [...staticStyles];

  // Process dynamic classes at runtime
  for (const dynamicClass of dynamicClasses) {
    if (!dynamicClass || typeof dynamicClass !== 'string') {
      continue;
    }

    // Split by whitespace if multiple classes in one interpolation
    const classes = dynamicClass.trim().split(/\s+/);

    for (const className of classes) {
      if (!className) continue;

      // Apply platform filtering
      if (!shouldApplyClass(className)) {
        continue;
      }

      // Get base class name (strip platform prefix if present)
      const baseClassName = getBaseClassName(className);

      // Look up in mainStyles or parse as arbitrary value
      const styleValue =
        mainStyles[baseClassName] || parseArbitraryValue(baseClassName);

      if (styleValue) {
        allStyles.push(styleValue);
      }
    }
  }

  // Flatten all styles
  const result = StyleSheet.flatten(allStyles as any);

  // Cache the result
  partialCache.set(cacheKey, result);

  return result;
}

/**
 * Platform-conditional helper
 * Returns different styles based on Platform.OS
 *
 * @param iosStyle - Style to use on iOS
 * @param androidStyle - Style to use on Android
 * @returns The appropriate style for the current platform
 */
export function _rnw_platform(
  iosStyle: StyleValue,
  androidStyle: StyleValue,
): StyleValue {
  return Platform.OS === 'ios' ? iosStyle : androidStyle;
}

/**
 * Clears the partial template cache
 * Useful when styles are customized at runtime
 */
export function _rnw_clearCache(): void {
  partialCache.clear();
}
