/**
 * Pre-computed style registry
 * This file is auto-generated by the Babel plugin at build time
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 *
 * Generated from mainStyles at build time for maximum performance
 */

import { mainStyles } from '../../core/mainStyles';

/**
 * Pre-computed styles - uses mainStyles directly at runtime
 * The Babel plugin generates inline style objects, so this is just a fallback
 *
 * Access pattern: precomputedStyles['m-4'] → { margin: 16 }
 */
export const precomputedStyles = new Proxy(
  {},
  {
    get(target: any, prop: string) {
      // Direct access to mainStyles at runtime
      // The Babel plugin should generate inline objects, but this provides fallback
      return mainStyles[prop];
    },
  },
);

/**
 * Static styles namespace for Babel plugin generated code
 * Maps style IDs to actual style objects
 */
export const staticStyles: Record<string, any> = {};

/**
 * Registers a static style at runtime (called by generated code)
 *
 * @param id - Unique style ID
 * @param classString - Original class string
 * @returns The style object
 */
export function registerStaticStyle(id: string, classString: string): any {
  if (staticStyles[id]) {
    return staticStyles[id];
  }

  // Parse the class string and create the style object
  const classNames = classString.trim().split(/\s+/);
  const styles = classNames.map(name => mainStyles[name]).filter(Boolean);

  // Flatten manually
  const flattened = styles.reduce((acc, style) => ({ ...acc, ...style }), {});

  staticStyles[id] = flattened;
  return flattened;
}

/**
 * Clears the cached registry
 * Called when styles are customized at runtime
 */
export function clearPrecomputedCache(): void {
  // Clear the static styles cache
  Object.keys(staticStyles).forEach(key => delete staticStyles[key]);
}
